# permissions for end users to edit podsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podset-editor-role
rules:
- apiGroups:
  - cache.github.com
  resources:
  - podsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.github.com
  resources:
  - podsets/status
  verbs:
  - get
